DEV: Improve test stability by waiting for async encrypt events (#216)
This was causing occasional failures in the discourse-assign tests when run with discourse-encrypt installed. This follows the same approach as add51b940e

```
Discourse Assign | Quick access assignments panel: Quick access assignments panel
---
actual: >
    null
stack: >
    TypeError: Cannot read properties of null (reading 'innerText')
        at Object.<anonymous> (http://localhost:7357/assets/plugins/test/discourse-assign_tests.js:973:28)
message: >
    Promise rejected during "Quick access assignments panel": Cannot read properties of null (reading 'innerText')
negative: >
    false
```